# version: "3.7"

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    container_name: redis_service
    image: redis:8.2
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  adminer: #put host as postgres_db #also issues with reloading on migration on running container(pruning volume doesn't work on a single container)
    container_name: postgres_client
    image: adminer:5.4.0
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  pgdata:
  redis_data:

networks:
  app-network:
    driver: bridge
