# version: "3.8"
# services:
#   postgres:
#     image: postgres
#     container_name: blog_db
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: passwrod
#       POSTGRES_DB: db
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
# volumes:
#   postgres_data:

version: "3.8"
services:
ervices:
  postgres:
    image: "postgres:16"
    container_name: my_postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default_database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped
  redis:
    image: "redis:7"
    container_name: redis-service
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
